import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar/Navbar";
import Landing from "../components/Landing/Landing";
import { client } from "../client/contentful";
import { createContext } from "react";
import { ICard } from "../@types/generated/contentful";

export const cardContext = createContext<ICard[]>([]);

export async function getStaticProps() {
  const res = await client.getEntries({ content_type: "card" });

  return {
    props: {
      cards: res.items,
    },
  };
}

const Home = ({ cards }: { cards: ICard[] }) => {
  return (
    <div>
      <Head>
        <title>Landig page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <cardContext.Provider value={cards}>
        <Landing />
      </cardContext.Provider>
    </div>
  );
};

export default Home;
