import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar/Navbar";
import "antd/dist/antd.css";
import { Content } from "antd/lib/layout/layout";

import Landing from "../components/content/Landing";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Landig page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Landing />
    </div>
  );
};

export default Home;
